
const TaskTypes = {
  LANDING_ZONE: 'LANDING_ZONE',
  CREATE_FOLDER: 'CREATE_FOLDER',
  SQL_EXECUTE: 'SQL_EXECUTE',
  WEB_DOWNLOAD: 'WEB_DOWNLOAD',
  GENERATE_CODE_FROM_T4_TEMPLATE: 'GENERATE_CODE_FROM_T4_TEMPLATE',
  COMPOSITE: 'COMPOSITE',
}

export default TaskTypes;