//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ultramarine.Generators.Language
{
	internal static partial class Constants
	{
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string DesignerFileExtension = "ugen";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductName = @"Ultramarine";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string CompanyName = @"Seavus";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductVersion = "1.0.0.0";

		// Menu definitions
		public static readonly global::System.ComponentModel.Design.CommandID GeneratorLanguageDiagramMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(GeneratorLanguageCommandSetId), 0x10000);
		public static readonly global::System.ComponentModel.Design.CommandID GeneratorLanguageExplorerMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(GeneratorLanguageCommandSetId), 0x10001);

		// Command definitions
		public static readonly global::System.ComponentModel.Design.CommandID ViewGeneratorLanguageExplorerCommand = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(GeneratorLanguageCommandSetId), 0x0001);
	
		// Package identifier
		public const string GeneratorLanguagePackageId = "253eb726-92cb-4387-9f64-2ca8bbc1e16a";
		
		// Editor factory identifier
		public const string GeneratorLanguageEditorFactoryId = "d2ea36cb-2ed1-4ccc-81c2-e69de04d530e";
		
		public const string DefaultDiagramExtension = ".diagram";
		
		// Model explorer tool window identifier
		public const string GeneratorLanguageModelExplorerToolWindowId = "9ae95886-a985-4bc2-9475-fc20306b55a6";
	}
}
//
// Constants not generated from values in DesignerDefinition.dsl are defined below
//
namespace Ultramarine.Generators.Language
{
	internal static partial class Constants
	{
		// Menu identifier
		public const string GeneratorLanguageCommandSetId = "13a59d26-29a0-4b72-b39b-57fa4305a8f5";
	}
}