//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Drawing.Design;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using System.Windows.Forms;
using VSShellInterop = global::Microsoft.VisualStudio.Shell.Interop;
using VSShell = global::Microsoft.VisualStudio.Shell;
using DslShell = global::Microsoft.VisualStudio.Modeling.Shell;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
using DslModeling = global::Microsoft.VisualStudio.Modeling;

namespace Ultramarine.Generators.Language
{
	/// <summary>
	/// This class implements the VS package that integrates this DSL into Visual Studio.
	/// </summary>
	[VSShell::PackageRegistration(RegisterUsing = VSShell::RegistrationMethod.Assembly, UseManagedResourcesOnly = true, AllowsBackgroundLoading = true)]
	[VSShell::ProvideToolWindow(typeof(GeneratorLanguageExplorerToolWindow), MultiInstances = false, Style = VSShell::VsDockStyle.Tabbed, Orientation = VSShell::ToolWindowOrientation.Right, Window = "{3AE79031-E1BC-11D0-8F78-00A0C9110057}")]
	[VSShell::ProvideToolWindowVisibility(typeof(GeneratorLanguageExplorerToolWindow), Constants.GeneratorLanguageEditorFactoryId)]
	[VSShell::ProvideStaticToolboxGroup("@Generator LanguageToolboxTab;Ultramarine.Generators.Language.Dsl.dll", "Ultramarine.Generators.Language.Generator LanguageToolboxTab")]
	[VSShell::ProvideStaticToolboxItem("Ultramarine.Generators.Language.Generator LanguageToolboxTab",
					"@ConnectedWithRelationshipToolboxItem;Ultramarine.Generators.Language.Dsl.dll", 
					"Ultramarine.Generators.Language.ConnectedWithRelationshipToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"ConnectExampleRelationF1Keyword", 
					"@ConnectedWithRelationshipToolboxBitmap;Ultramarine.Generators.Language.Dsl.dll", 
					0xff00ff,
					Index = 0)]
	[VSShell::ProvideStaticToolboxItem("Ultramarine.Generators.Language.Generator LanguageToolboxTab",
					"@BuildProjectToolboxItem;Ultramarine.Generators.Language.Dsl.dll", 
					"Ultramarine.Generators.Language.BuildProjectToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"BuildProject", 
					"@BuildProjectToolboxBitmap;Ultramarine.Generators.Language.Dsl.dll", 
					0xff00ff,
					Index = 1)]
	[VSShell::ProvideStaticToolboxItem("Ultramarine.Generators.Language.Generator LanguageToolboxTab",
					"@CreateFolderToolboxItem;Ultramarine.Generators.Language.Dsl.dll", 
					"Ultramarine.Generators.Language.CreateFolderToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"CreateFolder", 
					"@CreateFolderToolboxBitmap;Ultramarine.Generators.Language.Dsl.dll", 
					0xff00ff,
					Index = 2)]
	[VSShell::ProvideStaticToolboxItem("Ultramarine.Generators.Language.Generator LanguageToolboxTab",
					"@CreateProjectItemToolboxItem;Ultramarine.Generators.Language.Dsl.dll", 
					"Ultramarine.Generators.Language.CreateProjectItemToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"CreateProjectItem", 
					"@CreateProjectItemToolboxBitmap;Ultramarine.Generators.Language.Dsl.dll", 
					0xff00ff,
					Index = 3)]
	[VSShell::ProvideStaticToolboxItem("Ultramarine.Generators.Language.Generator LanguageToolboxTab",
					"@LoadCodeElementToolboxItem;Ultramarine.Generators.Language.Dsl.dll", 
					"Ultramarine.Generators.Language.LoadCodeElementToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"CreateExampleClassF1Keyword", 
					"@LoadCodeElementToolboxBitmap;Ultramarine.Generators.Language.Dsl.dll", 
					0xff00ff,
					Index = 4)]
	[VSShell::ProvideStaticToolboxItem("Ultramarine.Generators.Language.Generator LanguageToolboxTab",
					"@LoadProjectItemToolboxItem;Ultramarine.Generators.Language.Dsl.dll", 
					"Ultramarine.Generators.Language.LoadProjectItemToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"LoadProjectItem", 
					"@LoadProjectItemToolboxBitmap;Ultramarine.Generators.Language.Dsl.dll", 
					0xff00ff,
					Index = 5)]
	[VSShell::ProvideStaticToolboxItem("Ultramarine.Generators.Language.Generator LanguageToolboxTab",
					"@ReadPropertyToolboxItem;Ultramarine.Generators.Language.Dsl.dll", 
					"Ultramarine.Generators.Language.ReadPropertyToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"ReadProperty", 
					"@ReadPropertyToolboxBitmap;Ultramarine.Generators.Language.Dsl.dll", 
					0xff00ff,
					Index = 6)]
	[VSShell::ProvideStaticToolboxItem("Ultramarine.Generators.Language.Generator LanguageToolboxTab",
					"@SetVariableToolboxItem;Ultramarine.Generators.Language.Dsl.dll", 
					"Ultramarine.Generators.Language.SetVariableToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"SetVariable", 
					"@SetVariableToolboxBitmap;Ultramarine.Generators.Language.Dsl.dll", 
					0xff00ff,
					Index = 7)]
	[VSShell::ProvideStaticToolboxItem("Ultramarine.Generators.Language.Generator LanguageToolboxTab",
					"@IteratorToolboxItem;Ultramarine.Generators.Language.Dsl.dll", 
					"Ultramarine.Generators.Language.IteratorToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"Iterator", 
					"@IteratorToolboxBitmap;Ultramarine.Generators.Language.Dsl.dll", 
					0xff00ff,
					Index = 8)]
	[VSShell::ProvideStaticToolboxItem("Ultramarine.Generators.Language.Generator LanguageToolboxTab",
					"@TextTransformationToolboxItem;Ultramarine.Generators.Language.Dsl.dll", 
					"Ultramarine.Generators.Language.TextTransformationToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"TextTransformation", 
					"@TextTransformationToolboxBitmap;Ultramarine.Generators.Language.Dsl.dll", 
					0xff00ff,
					Index = 9)]
	[VSShell::ProvideStaticToolboxItem("Ultramarine.Generators.Language.Generator LanguageToolboxTab",
					"@ImporterToolboxItem;Ultramarine.Generators.Language.Dsl.dll", 
					"Ultramarine.Generators.Language.ImporterToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"Importer", 
					"@ImporterToolboxBitmap;Ultramarine.Generators.Language.Dsl.dll", 
					0xff00ff,
					Index = 10)]
	[VSShell::ProvideStaticToolboxItem("Ultramarine.Generators.Language.Generator LanguageToolboxTab",
					"@SqlCommandToolboxItem;Ultramarine.Generators.Language.Dsl.dll", 
					"Ultramarine.Generators.Language.SqlCommandToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"SqlCommand", 
					"@SqlCommandToolboxBitmap;Ultramarine.Generators.Language.Dsl.dll", 
					0xff00ff,
					Index = 11)]
	[VSShell::ProvideStaticToolboxItem("Ultramarine.Generators.Language.Generator LanguageToolboxTab",
					"@StringManipulationToolboxItem;Ultramarine.Generators.Language.Dsl.dll", 
					"Ultramarine.Generators.Language.StringManipulationToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"StringManipulation", 
					"@StringManipulationToolboxBitmap;Ultramarine.Generators.Language.Dsl.dll", 
					0xff00ff,
					Index = 12)]
	[VSShell::ProvideStaticToolboxItem("Ultramarine.Generators.Language.Generator LanguageToolboxTab",
					"@WebDownloadToolboxItem;Ultramarine.Generators.Language.Dsl.dll", 
					"Ultramarine.Generators.Language.WebDownloadToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"WebDownload", 
					"@WebDownloadToolboxBitmap;Ultramarine.Generators.Language.Dsl.dll", 
					0xff00ff,
					Index = 13)]
	[VSShell::ProvideEditorFactory(typeof(GeneratorLanguageEditorFactory), 103, TrustLevel = VSShellInterop::__VSEDITORTRUSTLEVEL.ETL_AlwaysTrusted)]
	[VSShell::ProvideEditorExtension(typeof(GeneratorLanguageEditorFactory), "." + Constants.DesignerFileExtension, 50)]
	[VSShell::ProvideEditorLogicalView(typeof(GeneratorLanguageEditorFactory), "{7651A702-06E5-11D1-8EBD-00A0C90F26EA}")] // Designer logical view GUID i.e. VSConstants.LOGVIEWID_Designer
	[DslShell::ProvideRelatedFile("." + Constants.DesignerFileExtension, Constants.DefaultDiagramExtension,
		ProjectSystem = DslShell::ProvideRelatedFileAttribute.CSharpProjectGuid,
		FileOptions = DslShell::RelatedFileType.FileName)]
	[DslShell::ProvideRelatedFile("." + Constants.DesignerFileExtension, Constants.DefaultDiagramExtension,
		ProjectSystem = DslShell::ProvideRelatedFileAttribute.VisualBasicProjectGuid,
		FileOptions = DslShell::RelatedFileType.FileName)]
	[DslShell::RegisterAsDslToolsEditor]
	[global::System.Runtime.InteropServices.ComVisible(true)]
	[DslShell::ProvideBindingPath]
	[DslShell::ProvideXmlEditorChooserBlockSxSWithXmlEditor(@"GeneratorLanguage", typeof(GeneratorLanguageEditorFactory))]

	internal abstract partial class GeneratorLanguagePackageBase : DslShell::AsyncModelingPackage
	{
		protected global::Ultramarine.Generators.Language.GeneratorLanguageToolboxHelper toolboxHelper;	
		
		/// <summary>
		/// Initialization method called by the package base class when this package is loaded.
		/// </summary>
		protected async override System.Threading.Tasks.Task InitializeAsync(CancellationToken cancellationToken, IProgress<VSShell.ServiceProgressData> progress)
		{
			await base.InitializeAsync(cancellationToken, progress);

			// Register the editor factory used to create the DSL editor.
			this.RegisterEditorFactory(new GeneratorLanguageEditorFactory(this));
			
			// Initialize the toolbox helper
			toolboxHelper = new global::Ultramarine.Generators.Language.GeneratorLanguageToolboxHelper(this);

			// Create the command set that handles menu commands provided by this package.
			GeneratorLanguageCommandSet commandSet = new GeneratorLanguageCommandSet(this);
			await commandSet.InitializeAsync(cancellationToken);
			
			// Create the command set that handles cut/copy/paste commands provided by this package.
			GeneratorLanguageClipboardCommandSet clipboardCommandSet = new GeneratorLanguageClipboardCommandSet(this);
			await clipboardCommandSet.InitializeAsync(cancellationToken);
			
			// Register the model explorer tool window for this DSL.
			this.AddToolWindow(typeof(GeneratorLanguageExplorerToolWindow));

			if (cancellationToken.IsCancellationRequested)
			{
				return;
			}

			await JoinableTaskFactory.SwitchToMainThreadAsync();

			// Initialize Extension Registars
			// this is a partial method call
			this.InitializeExtensions();

			// Add dynamic toolbox items
			await this.SetupDynamicToolboxAsync(cancellationToken);
		}

		/// <summary>
		/// Partial method to initialize ExtensionRegistrars (if any) in the DslPackage
		/// </summary>
		partial void InitializeExtensions();
		
		/// <summary>
		/// Returns any dynamic tool items for the designer
		/// </summary>
		/// <remarks>The default implementation is to return the list of items from the generated toolbox helper.</remarks>
		protected override global::System.Collections.Generic.IList<DslDesign::ModelingToolboxItem> CreateToolboxItems()
		{
			try
			{
				Debug.Assert(toolboxHelper != null, "Toolbox helper is not initialized");
				return toolboxHelper.CreateToolboxItems();
			}
			catch (global::System.Exception e)
			{
				global::System.Diagnostics.Debug.Fail("Exception thrown during toolbox item creation.  This may result in Package Load Failure:\r\n\r\n" + e);
				throw;
			}
		}
		
		
		/// <summary>
		/// Given a toolbox item "unique ID" and a data format identifier, returns the content of
		/// the data format. 
		/// </summary>
		/// <param name="itemId">The unique ToolboxItem to retrieve data for</param>
		/// <param name="format">The desired format of the resulting data</param>
		protected override object GetToolboxItemData(string itemId, DataFormats.Format format)
		{
			Debug.Assert(toolboxHelper != null, "Toolbox helper is not initialized");
		
			// Retrieve the specified ToolboxItem from the DSL
			return toolboxHelper.GetToolboxItemData(itemId, format);
		}

		public override VSShellInterop::IVsAsyncToolWindowFactory GetAsyncToolWindowFactory(Guid toolWindowType)
		{
			if (toolWindowType == typeof(GeneratorLanguageExplorerToolWindow).GUID)
			{
				return this;
			}

			return base.GetAsyncToolWindowFactory(toolWindowType);
		}
	}
}

//
// Package attributes which may need to change are placed on the partial class below, rather than in the main include file.
//
namespace Ultramarine.Generators.Language
{
	/// <summary>
	/// Double-derived class to allow easier code customization.
	/// </summary>
	[VSShell::ProvideMenuResource("1000.ctmenu", 1)]
	[VSShell::ProvideToolboxItems(1)]
	[global::Microsoft.VisualStudio.TextTemplating.VSHost.ProvideDirectiveProcessor(typeof(global::Ultramarine.Generators.Language.GeneratorLanguageDirectiveProcessor), global::Ultramarine.Generators.Language.GeneratorLanguageDirectiveProcessor.GeneratorLanguageDirectiveProcessorName, "A directive processor that provides access to GeneratorLanguage files")]
	[global::System.Runtime.InteropServices.Guid(Constants.GeneratorLanguagePackageId)]
	internal sealed partial class GeneratorLanguagePackage : GeneratorLanguagePackageBase
	{
	}
}